### ISSUE TITLE
Doesn't work on macOS arm64 hardware

### ISSUE THREAD

**Issue by Nezteb** [jtakakura/asdf-odin#1]
**Describe the bug**

[Odin does support macOS using ARM](https://odin-lang.org/docs/install/#support), but [Odin doesn't publish ARM builds for macOS](https://github.com/odin-lang/Odin/discussions/2830). This won't be fixable/closable until that time. 😅 

**Steps to reproduce**

1. Use an M1 or M2 macOS machine.
2. Install `asdf` and `asdf-odin`.
3. Install of Odin with:
  1. `asdf install odin dev-2023-08` (or whatever the latest version is)
  2. `asdf global odin dev-2023-08`
4. Try to run `odin`.
5. Notice error:
```
dyld[19872]: Library not loaded: /usr/local/opt/llvm@11/lib/libLLVM-C.dylib
  Referenced from: <0A12B3D4-P0YU-8273-JKL4-1AB23C4BCE9F> /Users/noah/.asdf/installs/odin/dev-2023-08/bin/odin
  Reason: tried: '/usr/local/opt/llvm@11/lib/libLLVM-C.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/llvm@11/lib/libLLVM-C.dylib' (no such file), '/usr/local/opt/llvm@11/lib/libLLVM-C.dylib' (no such file), '/usr/local/lib/libLLVM-C.dylib' (no such file), '/usr/lib/libLLVM-C.dylib' (no such file, not in dyld cache)
[1]    19872 abort      odin
```

**Expected behavior**

Ideally running Odin installed via `asdf-odin` would work on arm64 macOS machines.

**Additional context**

Once Odin starts publishing arm64 builds, `asdf-odin` will need a couple modifications to switch on the output of `uname -m` to differentiate between `x84_64` and `arm64`. 😄

**Comment by jtakakura** [comment]
@Nezteb asdf-odin downloads the release binaries of Odin from GitHub.
Currently, the binaries are only distributed for amd64, so I cannot support other architectures like arm64.

https://github.com/odin-lang/Odin/releases

**Comment by Nezteb** [comment]
@jtakakura Yep! I just wanted to create this GH issue as a placeholder so that it is not forgotten.

If/when Odin is able to start publishing ARM releases to GitHub, we can look at pulling those with `asdf-odin`. 😄

**Comment by jtakakura** [comment]
Ah, I see. Thanks for creating this issue.
