### ISSUE TITLE
Odin installed via asdf-odin plugin complains for missing libLLVM-18.so.18.1

### ISSUE THREAD

**Issue by yudistrange** [jtakakura/asdf-odin#10]
Odin installed via asdf-odin doesn't work on Arch linux. Even though the requisite libLLVM is installed.
Should I just create a symlink of `libLLVM-18.so.18.1 -> libLLVM.so.18.1` on my system manually?

```
❯ odin --version
/home/user/.asdf/installs/odin/dev-2024-08/bin/odin: error while loading shared libraries: libLLVM-18.so.18.1: cannot open shared object file: No such file or directory


❯ ls /usr/lib/ | grep  libLLVM
libLLVM.so -> libLLVM.so.18.1
libLLVM-18.so -> libLLVM.so.18.1
libLLVM.so.18.1
libLLVMDemangle.a
libLLVMDebuginfod.a
libLLVMSupport.a
libLLVMTableGen.a
libLLVMTestingAnnotations.a
libLLVMTestingSupport.a
```

**Steps to reproduce**

1. Install any version of Odin from asdf-odin
2. Try running odin installed via asdf

**Expected behavior**

Odin should run without complaining about missing dependency.

**Additional context**
If I install `odin` via the `yay` command, it works without a hitch. It doesn't install a separate libLLVM version.

**Comment by achou11** [comment]
@yudistrange are you experiencing the issue after updating the plugin and installing dev-2024-10? I just did that and this issue is no longer happening to me

**Comment by yudistrange** [comment]
I updated my plugin and installed the latest version of odin. The issue has been resolved. Closing.
Thank you @achou11 :+1:
