### ISSUE TITLE
Unable to install dev-2024-10 on Linux due to renamed release asset

### ISSUE THREAD

**Issue by achou11** [jtakakura/asdf-odin#11]
Looks like https://github.com/odin-lang/Odin/releases/tag/dev-2024-10 renamed the Linux-related asset from `
odin-ubuntu-amd64-dev-2024-10.zip ` to `odin-linux-amd64-dev-2024-10.zip`

**Comment by hqnna** [comment]
I've created a fork of this plugin over [here](https://github.com/hqnna/asdf-odin) that fixes this.
