### ISSUE TITLE
Cannot install dev-2024-11 on linux

### ISSUE THREAD

**Issue by rkyleg** [jtakakura/asdf-odin#13]
**Describe the bug**

The folder inside the zip file is now a gzip file called dist.tar.gz  with a similar folder name as previous releases inside it

**Screenshots**
![image](https://github.com/user-attachments/assets/6970a55c-ce04-46fa-b0c0-563596565ad0)
![image](https://github.com/user-attachments/assets/75722e22-3349-4ead-8638-d244c245d6c5)

**Comment by jtakakura** [comment]
@rkyleg  The issue should have been resolved in Pull Request #12. 
Could you please confirm?

**Comment by rkyleg** [comment]
@jtakakura the pull request fixed it for me too. thanks for creating this!
